max_guest_topic_views:
  type: string
  default: "1"
  description: Number of topic views until gate displays. After the gate first appears, it appears randomly between 1 and this number.
dismissable_false:
  type: bool
  default: false
  description: Removes the close button and lock the modal so visitors can't close it.
use_gate_buttons:
  type: bool
  default: false
  description: Use buttons on modal footer instead of links.
login_button_style:
  type: enum
  default: btn-primary
  choices:
    - btn-default
  description: Guest Gate Login button style. btn-primary is a blue (tertiary) colored button by default. btn-default is a grey (primary-low) colored button by default.
signup_button_style:
  type: enum
  default: btn-default
  choices:
    - btn-primary
  description: Guest Gate Signup button style. btn-primary is a blue (tertiary) colored button by default. btn-default is a grey (primary-low) colored button by default.
custom_url_enabled:
  type: bool
  default: false
  description: Enable custom url for Guest Gate Login and Sing Up button / link. By default this is redirect the visitor after click the Guest Gate Login or Signup button to the homepage and open Login or Signup modal
custom_login_url:
  type: string
  default: "/login"
  description: Add custom url to Guest Gate Login button / link. By default (/login) this is redirect to home page and open login modal.
custom_signup_url:
  type: string
  default: "/signup"
  description: Add custom url to Guest Gate Sign Up button / link. By default (/signup) this is redirect to home page and open signup modal.
gate_footer_position:
  default: center
  type: enum
  choices:
    - left
    - right
  description: Footer buttons/links position.
gate_show_only_once:
  type: bool
  default: false
  description: Guest Gate modal show only once per session.
custom_gate_enabled:
  type: bool
  default: false
custom_gate_image:
  type: upload
  default: ""
custom_gate_image_width:
  type: string
  default: "150px"
custom_gate_big_text_color:
  type: string
  default: "var(--primary)"
custom_gate_little_text_color:
  type: string
  default: "var(--primary)"
custom_gate_background_color:
  type: string
  default: "var(--secondary)"
custom_gate_link_color:
  type: string
  default: "var(--primary-medium)"
